#!/usr/bin/bash

COMMAND=$1

shift 1

DEST=$@

ROOT=$(dirname -- "$( readlink -f -- "$0"; )")

help() {
    echo -e "\n\e[1mstickee Canary\e[0m\nPHP Code style tools\n"
    echo -e "    \e[1minstall\e[0m : copies the config files"
    echo -e "\nAvailable commands:\n"
    echo -e "    \e[1manalyse\e[0m : runs PHPStan"
    echo -e "    \e[1mfix\e[0m     : runs PHP CS Fixer"
    echo -e "    \e[1msuggest\e[0m : runs Rector in dry run mode"
    echo -e "    \e[1mimprove\e[0m : attempts to improve the code"
}

install() {
    if [ -z $DEST ]; then
        echo -e "\e[1;31mYou must provide a destination.\e[0m"
    else
        if [ ! -d $DEST ]; then
            echo -e "\e[1;31mThe '$DEST' directory does not exist.\e[0m\n"
            input=Y
            read -r -p "Create it now? [Y/n]" input
            input=${input:-Y}
            case $input in
                [yY][eE][sS]|[yY])
                    mkdir $DEST
                    echo "created $DEST directory"
                    ;;
                [nN][oO]|[nN])
                    echo -e "\nexiting..."
                    exit 1
                    ;;
                *)
                    echo -e "\nexiting..."
                    exit 1
                    ;;
            esac
        fi

        echo -e "\n\e[1;32mInstalling Canary files into \"$DEST\"\e[0m\n"
        cp -urv $ROOT/../php-cs-fixer-config/dist/. $DEST
        cp -urv $ROOT/../larastan-config/dist/. $DEST
        cp -urv $ROOT/../rector-config/dist/. $DEST
        cp -rv $ROOT/dist/. $DEST

        if [ ! -f "$DEST/.gitignore" ]; then
            echo -e "\n\e[1;31mCould not update your .gitignore\e[0m"
            echo -e "\e[1;31mYou need to manually add '.php-cs-fixer.cache' to your .gitignore file\e[0m"
        else
            GITIGNORE_CONTAINS_PHP_CS_FIXER_CACHE=$(cat $DEST/.gitignore | grep '.php-cs-fixer.cache' | wc -l)
            if [ $GITIGNORE_CONTAINS_PHP_CS_FIXER_CACHE -eq 0 ]; then
                echo -e "\nadding '.php-cs-fixer.cache' to your .gitignore file..."
                echo ".php-cs-fixer.cache" >> $DEST/.gitignore
            fi
        fi
        
        echo -e "\n\e[1;32mDone\e[0m"
        echo -e "\n\e[1;33mRemember to check and configure any new files.\e[0m"
    fi
}

fix() {
    $ROOT/vendor/bin/php-cs-fixer fix $@
}

analyse() {
    $ROOT/vendor/bin/phpstan analyse $@
}

improve() {
    $ROOT/vendor/bin/rector process $@
    $ROOT/vendor/bin/php-cs-fixer fix $@
}

suggest() {
    $ROOT/vendor/bin/rector process $@ --dry-run
}

if [[ -z $COMMAND ]]; then
    help
elif [ $COMMAND == "install" ]; then
    install
elif [ $COMMAND == "fix" ]; then
    fix
elif [ $COMMAND == "analyse" ]; then
    analyse
elif [ $COMMAND == "improve" ]; then
    improve
elif [ $COMMAND == "suggest" ]; then
    suggest
else
    echo -e "\e[1;31m$COMMAND\e[31m is an unrecognised command.\e[0m"
    help
fi