name: PHP Tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        php: [ 8.1, 8.2 ]

    name: PHP v${{ matrix.php }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "${{ matrix.php }}"
      - name: Execute tests
        run: vendor/bin/pest

